obj-$(CONFIG_NET_DSA_YT921X) += yt921x_driver.o
yt921x_driver-y := \
	yt921x.o \
	yt921x_core.o \
	yt921x_mbus.o \
	yt921x_qos_tc.o \
	yt921x_l2.o \
	yt921x_port.o \
	yt921x_chip.o \
	yt921x_debugfs.o yt921x_acl.o
